name: My First CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    container: node:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: hostname
      - run: whoami
      - run: hostname -I
      - run: |
          echo "Hello from GitHub Actions"
          node --version
          npm --version
          cat /etc/os-release
          ls -la
          date
